### ISSUE TITLE
Resources url shouldn't be hardcoded

### ISSUE THREAD

**Issue by psociety** [mathishouis/scuti-renderer#38]
Resources url is hardcoded to localhost, leaving no room to actually use the renderer. The url should be customizable:
https://github.com/kozennnn/scuti-renderer/blob/dev/src/Scuti.ts#L92

```js
        Assets.add("room/materials", "http://127.0.0.1:8081/generic/room/room_data.json");
        Assets.add("room/room", "http://127.0.0.1:8081/generic/room/room.json");
        Assets.add("room/cursors", "http://127.0.0.1:8081/generic/tile_cursor/tile_cursor.json");
        Assets.add("furnitures/floor/placeholder", "http://127.0.0.1:8081/generic/place_holder/place_holder_furniture.json");
        Assets.add("furnitures/furnidata", "http://127.0.0.1:8081/gamedata/furnidata.json");
        Assets.add("figures/figuredata", "http://127.0.0.1:8081/gamedata/figuredata.json");
        Assets.add("figures/figuremap", "http://127.0.0.1:8081/gamedata/figuremap.json");
        Assets.add("figures/draworder", "http://127.0.0.1:8081/gamedata/draworder.json");
        Assets.add("figures/actions", "http://127.0.0.1:8081/generic/HabboAvatarActions.json");
        Assets.add("figures/partsets", "http://127.0.0.1:8081/generic/HabboAvatarPartSets.json");
        Assets.add("figures/animations", "http://127.0.0.1:8081/generic/HabboAvatarAnimations.json");
```

I've used GitHub pages to host the resources at https://psociety.github.io/scuti-resources/ it that helps. At least it would be more accessible than expecting localhost self serving. It should also be done at https://github.com/kozennnn/scuti-resources so it can officially be used.

**Comment by tetreum** [comment]
The problem is that not only this urls are hardcoded, but there are some deep inside the code, like:
https://github.com/kozennnn/scuti-renderer/blob/dev/src/objects/avatars/Avatar.ts#L70
https://github.com/kozennnn/scuti-renderer/blob/dev/src/objects/avatars/AvatarBodyPart.ts#L40
https://github.com/kozennnn/scuti-renderer/blob/dev/src/objects/furnitures/FurnitureView.ts#L70

So the issue is bigger as those parts have no way to reach room config and i believe there is no global instance where the domain config can be stored.
